"""add train stop distance tables

Revision ID: 0153c1191149
Revises: 28e9bb5425c7
Create Date: 2026-05-04 18:07:30.907058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0153c1191149'
down_revision: Union[str, Sequence[str], None] = '28e9bb5425c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS train_stop_distance")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='train_stop_distance'
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_train_stop_distance', sa.Float(), nullable=False),
    sa.Column('correct_train_stop_distance', sa.Float(), nullable=False),
    sa.Column('distance_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['train_stop_distance.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='train_stop_distance'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts', schema='train_stop_distance')
    op.drop_table('problems', schema='train_stop_distance')
    op.execute("DROP SCHEMA IF EXISTS train_stop_distance CASCADE")
    # ### end Alembic commands ###
