"""add straight line acceleration tables

Revision ID: 28e9bb5425c7
Revises: fe0e12375e1e
Create Date: 2026-05-02 18:36:06.596832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e9bb5425c7'
down_revision: Union[str, Sequence[str], None] = 'fe0e12375e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS straight_line_acceleration")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='straight_line_acceleration'
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_straight_line_acceleration', sa.Float(), nullable=False),
    sa.Column('correct_straight_line_acceleration', sa.Float(), nullable=False),
    sa.Column('time_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['straight_line_acceleration.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='straight_line_acceleration'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts', schema='straight_line_acceleration')
    op.drop_table('problems', schema='straight_line_acceleration')
    op.execute("DROP SCHEMA IF EXISTS straight_line_acceleration CASCADE")
    # ### end Alembic commands ###
