"""add river_jump_velocity schema and tables

Revision ID: 45f13eddcf22
Revises: 54ad34de00bb
Create Date: 2026-05-20 16:35:26.248891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f13eddcf22'
down_revision: Union[str, Sequence[str], None] = '54ad34de00bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS river_jump_velocity")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('x_f', sa.Float(), nullable=False),
    sa.Column('y_i', sa.Float(), nullable=False),
    sa.Column('y_f', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='river_jump_velocity'
    )
    op.create_table('attempt_a',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_x_velocity', sa.Float(), nullable=False),
    sa.Column('correct_x_velocity', sa.Float(), nullable=False),
    sa.Column('velocity_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['river_jump_velocity.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='river_jump_velocity'
    )
    op.create_table('attempt_b',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_final_velocity', sa.Float(), nullable=False),
    sa.Column('correct_final_velocity', sa.Float(), nullable=False),
    sa.Column('final_velocity_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['river_jump_velocity.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='river_jump_velocity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt_b', schema='river_jump_velocity')
    op.drop_table('attempt_a', schema='river_jump_velocity')
    op.drop_table('problems', schema='river_jump_velocity')
    op.execute("DROP SCHEMA IF EXISTS river_jump_velocity CASCADE")
    # ### end Alembic commands ###
