"""add bird instantaneous velocity tables

Revision ID: 4cd2b1849387
Revises: 0153c1191149
Create Date: 2026-05-07 20:09:25.512737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd2b1849387'
down_revision: Union[str, Sequence[str], None] = '0153c1191149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS bird_instantaneous_velocity")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('function_type', sa.String(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bird_instantaneous_velocity'
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_bird_instantaneous_velocity', sa.Float(), nullable=False),
    sa.Column('correct_bird_instantaneous_velocity', sa.Float(), nullable=False),
    sa.Column('velocity_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['bird_instantaneous_velocity.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bird_instantaneous_velocity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts', schema='bird_instantaneous_velocity')
    op.drop_table('problems', schema='bird_instantaneous_velocity')
    op.execute("DROP SCHEMA IF EXISTS bird_instantaneous_velocity CASCADE")
    # ### end Alembic commands ###
