"""add squirrel_position_and_velocity_vectors schema and tables

Revision ID: 54ad34de00bb
Revises: c1b226311b81
Create Date: 2026-05-14 07:47:09.035984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ad34de00bb'
down_revision: Union[str, Sequence[str], None] = 'c1b226311b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS squirrel_position_and_velocity_vectors")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('a_x', sa.Float(), nullable=False),
    sa.Column('b_x', sa.Float(), nullable=False),
    sa.Column('c_y', sa.Float(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='squirrel_position_and_velocity_vectors'
    )
    op.create_table('attempt_a',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_a_x', sa.Float(), nullable=False),
    sa.Column('student_b_x', sa.Float(), nullable=False),
    sa.Column('student_c_y', sa.Float(), nullable=False),
    sa.Column('correct_a_x', sa.Float(), nullable=False),
    sa.Column('correct_b_x', sa.Float(), nullable=False),
    sa.Column('correct_c_y', sa.Float(), nullable=False),
    sa.Column('coefficient_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['squirrel_position_and_velocity_vectors.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='squirrel_position_and_velocity_vectors'
    )
    op.create_table('attempt_b',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_distance', sa.Float(), nullable=False),
    sa.Column('correct_distance', sa.Float(), nullable=False),
    sa.Column('distance_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['squirrel_position_and_velocity_vectors.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='squirrel_position_and_velocity_vectors'
    )
    op.create_table('attempt_c',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_magnitude', sa.Float(), nullable=False),
    sa.Column('correct_magnitude', sa.Float(), nullable=False),
    sa.Column('student_direction', sa.Float(), nullable=False),
    sa.Column('correct_direction', sa.Float(), nullable=False),
    sa.Column('magnitude_and_direction_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['squirrel_position_and_velocity_vectors.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='squirrel_position_and_velocity_vectors'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt_c', schema='squirrel_position_and_velocity_vectors')
    op.drop_table('attempt_b', schema='squirrel_position_and_velocity_vectors')
    op.drop_table('attempt_a', schema='squirrel_position_and_velocity_vectors')
    op.drop_table('problems', schema='squirrel_position_and_velocity_vectors')
    op.execute("DROP SCHEMA IF EXISTS squirrel_position_and_velocity_vectors CASCADE")
    # ### end Alembic commands ###
