"""add_relay_catchup_time_tables

Revision ID: c1b226311b81
Revises: 4cd2b1849387
Create Date: 2026-05-09 22:48:16.363690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b226311b81'
down_revision: Union[str, Sequence[str], None] = '4cd2b1849387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS relay_catchup_time")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b_one', sa.Float(), nullable=False),
    sa.Column('b_two', sa.Float(), nullable=False),
    sa.Column('v_one', sa.Float(), nullable=False),
    sa.Column('v_two', sa.Float(), nullable=False),
    sa.Column('s_one', sa.Float(), nullable=False),
    sa.Column('s_two', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='relay_catchup_time'
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_relay_catchup_time', sa.Float(), nullable=False),
    sa.Column('correct_relay_catchup_time', sa.Float(), nullable=False),
    sa.Column('time_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['relay_catchup_time.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='relay_catchup_time'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts', schema='relay_catchup_time')
    op.drop_table('problems', schema='relay_catchup_time')
    op.execute("DROP SCHEMA IF EXISTS relay_catchup_time CASCADE")
    # ### end Alembic commands ###
