"""initial migration

Revision ID: fe0e12375e1e
Revises: 
Create Date: 2026-04-26 15:26:34.397385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0e12375e1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS drop_time")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('walker_start', sa.Float(), nullable=False),
    sa.Column('walker_velocity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='drop_time'
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('student_drop_time', sa.Float(), nullable=False),
    sa.Column('correct_drop_time', sa.Float(), nullable=False),
    sa.Column('target_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['drop_time.problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='drop_time'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts', schema='drop_time')
    op.drop_table('problems', schema='drop_time')
    op.execute("DROP SCHEMA IF EXISTS drop_time CASCADE")
    # ### end Alembic commands ###
